### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by dac514** [hasegawa-tomoki/php-terminal-nes-emulator#5]
Have you seen this fork?

https://github.com/sj-i/php-terminal-nes-emulator/tree/optimize

> I've gone from 5fps to 10fps just like that.

**Comment by hasegawa-tomoki** [comment]
Thanks for your information.  
Yes, I know that and I tried.  
But I can't see fps gain with super Mario bros.  
So, now, I want to keep code readability.
